(function(){'use strict';
var e="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},h="object"===typeof e.global&&e.global?e.global:"object"===typeof global&&global&&global.Object===Object?global:this;e.global=h;var m="object"===typeof e.exportsNamespace&&e.exportsNamespace?e.exportsNamespace:h;e.exportsNamespace=m;h.Object.freeze(e);var aa={envInfo:e,semantics:{asInstanceOfs:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.13"};h.Object.freeze(aa);h.Object.freeze(aa.semantics);
var ba=h.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},n=h.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},p=0,q=h.WeakMap?new h.WeakMap:null;function r(a){return function(b,c){return!(!b||!b.a||b.a.l!==c||b.a.j!==a)}}function ca(a){for(var b in a)return b}
function da(a,b,c){var d=new a.G(b[c]);if(c<b.length-1){a=a.n;c+=1;for(var g=d.E,f=0;f<g.length;f++)g[f]=da(a,b,c)}return d}function ea(a){switch(typeof a){case "string":return u(fa);case "number":var b=a|0;return b===a?b<<24>>24===b&&1/b!==1/-0?u(ga):b<<16>>16===b&&1/b!==1/-0?u(ha):u(ia):"number"===typeof a?u(ja):u(ka);case "boolean":return u(la);case "undefined":return u(ma);default:return null===a?a.na():a&&a.a&&a.a.g.D?u(na):a&&a.a?u(a.a):null}}
function oa(a){switch(typeof a){case "string":pa||(pa=(new v).c());for(var b=0,c=1,d=-1+(a.length|0)|0;0<=d;)b=b+ba(65535&(a.charCodeAt(d)|0),c)|0,c=ba(31,c),d=-1+d|0;return b;case "number":w||(w=(new x).c());b=w;c=a|0;if(c===a&&-Infinity!==1/a)b=c;else{if(b.h)b.I[0]=a,b=y(b.v[b.L]|0,b.v[b.J]|0);else{if(a!==a)b=!1,a=2047,c=+h.Math.pow(2,51);else if(Infinity===a||-Infinity===a)b=0>a,a=2047,c=0;else if(0===a)b=-Infinity===1/a,c=a=0;else if(d=(b=0>a)?-a:a,d>=+h.Math.pow(2,-1022)){a=+h.Math.pow(2,52);
var c=+h.Math.log(d)/.6931471805599453,c=+h.Math.floor(c)|0,c=1023>c?c:1023,g=d/+h.Math.pow(2,c)*a,d=+h.Math.floor(g),g=g-d,d=.5>g?d:.5<g?1+d:0!==d%2?1+d:d;2<=d/a&&(c=1+c|0,d=1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=a);a=c;c=d}else a=d/+h.Math.pow(2,-1074),c=+h.Math.floor(a),d=a-c,a=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c;c=+c;b=y(c|0,(b?-2147483648:0)|(a|0)<<20|c/4294967296|0)}b=b.w^b.u}return b;case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.a||null===a?a.B():null===q?42:
ra(a)}}function sa(a,b){var c=h.Object.getPrototypeOf,d=h.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var g=d(a,b);if(void 0!==g)return g;a=c(a)}}function ta(a,b,c){a=sa(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}function ua(a,b,c,d){a=sa(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new h.TypeError("super has no setter '"+c+"'.");}
var ra=null!==q?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return oa(a);default:if(null===a)return 0;var b=q.get(a);void 0===b&&(p=b=p+1|0,q.set(a,b));return b}}:function(a){if(a&&a.a){var b=a.$idHashCode$0;if(void 0!==b)return b;if(h.Object.isSealed(a))return 42;p=b=p+1|0;return a.$idHashCode$0=b}return null===a?0:oa(a)};this.__ScalaJSExportsNamespace=m;
function z(){this.x=this.G=void 0;this.j=this.n=this.g=null;this.l=0;this.F=null;this.t="";this.e=this.r=this.s=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function A(a,b,c){var d=new z;d.g={};d.n=null;d.F=a;d.t=b;d.e=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function B(a,b,c,d,g,f,k){var l=new z,t=ca(a);f=f||function(a){return!!(a&&a.a&&a.a.g[t])};k=k||function(a,b){return!!(a&&a.a&&a.a.l===b&&a.a.j.g[t])};l.x=g;l.g=c;l.t="L"+b+";";l.e=k;l.name=b;l.isInterface=!1;l.isRawJSType=!!d;l.isInstance=f;return l}
function va(a){function b(a){if("number"===typeof a){this.E=Array(a);for(var b=0;b<a;b++)this.E[b]=g}else this.E=a}var c=new z,d=a.F,g="longZero"==d?C().z:d;b.prototype=new D;b.prototype.constructor=b;b.prototype.a=c;var d="["+a.t,f=a.j||a,k=a.l+1;c.G=b;c.x=wa;c.g={b:1,qa:1,d:1};c.n=a;c.j=f;c.l=k;c.F=null;c.t=d;c.s=void 0;c.r=void 0;c.e=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return f.e(a,k)};return c}
function u(a){if(!a.s){var b=new E;b.o=a;a.s=b}return a.s}z.prototype.getFakeInstance=function(){return this===fa?"some string":this===la?!1:this===ga||this===ha||this===ia||this===ja||this===ka?0:this===na?C().z:this===ma?void 0:{a:this}};z.prototype.getSuperclass=function(){return this.x?u(this.x):null};z.prototype.getComponentType=function(){return this.n?u(this.n):null};z.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b.r||(b.r=va(b)),b=b.r;return da(b,a,0)};
var xa=A(!1,"Z","boolean"),ya=A(0,"C","char"),za=A(0,"B","byte"),Aa=A(0,"S","short"),Ba=A(0,"I","int"),Ca=A("longZero","J","long"),Da=A(0,"F","float"),Ea=A(0,"D","double");xa.e=r(xa);ya.e=r(ya);za.e=r(za);Aa.e=r(Aa);Ba.e=r(Ba);Ca.e=r(Ca);Da.e=r(Da);Ea.e=r(Ea);function F(){}function D(){}D.prototype=F.prototype;F.prototype.c=function(){return this};F.prototype.q=function(){var a=ea(this).o.name,b=(+(this.B()>>>0)).toString(16);return a+"@"+b};F.prototype.B=function(){return ra(this)};F.prototype.toString=function(){return this.q()};var wa=B({b:0},"java.lang.Object",{b:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.a){var c=a.l||0;return!(c<b)&&(c>b||!a.j.isPrimitive)}return!1});F.prototype.a=wa;function G(){}G.prototype=new D;
G.prototype.constructor=G;G.prototype.c=function(){return this};
function Fa(a){var b=a.getContext("2d");a.width=a.parentElement.clientWidth|0;a.height=a.parentElement.clientHeight|0;var c=(a.width|0)+"x"+(a.height|0);Ga(Ha().C.y,c+"\n");c=a.id;Ga(Ha().C.y,c+"\n");b.fillStyle="#f8f8F8";b.fillRect(0,0,a.width|0,a.height|0);b.fillStyle="black";c=Ia();a.onmousedown=function(a){return function(){a.p=!0}}(c);a.onmouseup=function(a){return function(){a.p=!1}}(c);a.onmousemove=function(a,b,c){return function(k){var l=a.getBoundingClientRect();c.p&&b.fillRect(+k.clientX-
+l.left,+k.clientY-+l.top,10,10)}}(a,b,c)}G.prototype.main=function(a){Fa(a)};G.prototype.a=B({N:0},"example.ScalaJSExample$",{N:1,b:1});var H=void 0;m.example=m.example||{};m.example.ScalaJSExample=function(){H||(H=(new G).c());return H};function E(){this.o=null}E.prototype=new D;E.prototype.constructor=E;E.prototype.q=function(){return(this.o.isInterface?"interface ":this.o.isPrimitive?"":"class ")+this.o.name};E.prototype.a=B({W:0},"java.lang.Class",{W:1,b:1});function I(){this.H=this.M=null}
I.prototype=new D;I.prototype.constructor=I;I.prototype.c=function(){J=this;this.M=Ja(!1);this.H=Ja(!0);return this};I.prototype.a=B({da:0},"java.lang.System$",{da:1,b:1});var J=void 0;function Ka(){J||(J=(new I).c());return J}function K(){}K.prototype=new D;K.prototype.constructor=K;function Ma(){}Ma.prototype=K.prototype;function L(){this.y=null}L.prototype=new D;L.prototype.constructor=L;L.prototype.q=function(){return"DynamicVariable("+this.y+")"};function M(a,b){a.y=b;return a}
L.prototype.a=B({fa:0},"scala.util.DynamicVariable",{fa:1,b:1});function x(){this.h=!1;this.I=this.v=this.k=null;this.A=!1;this.L=this.J=0}x.prototype=new D;x.prototype.constructor=x;
x.prototype.c=function(){w=this;this.k=(this.h=!!(h.ArrayBuffer&&h.Int32Array&&h.Float32Array&&h.Float64Array))?new h.ArrayBuffer(8):null;this.v=this.h?new h.Int32Array(this.k,0,2):null;this.h&&new h.Float32Array(this.k,0,2);this.I=this.h?new h.Float64Array(this.k,0,1):null;if(this.h)this.v[0]=16909060,a=1===((new h.Int8Array(this.k,0,8))[0]|0);else var a=!0;this.J=(this.A=a)?0:1;this.L=this.A?1:0;return this};x.prototype.a=B({ga:0},"scala.scalajs.runtime.Bits$",{ga:1,b:1});var w=void 0;
function v(){}v.prototype=new D;v.prototype.constructor=v;v.prototype.c=function(){return this};v.prototype.a=B({ia:0},"scala.scalajs.runtime.RuntimeString$",{ia:1,b:1});var pa=void 0;function N(){}N.prototype=new D;N.prototype.constructor=N;function Na(){}Na.prototype=N.prototype;function O(){this.p=!1}O.prototype=new D;O.prototype.constructor=O;O.prototype.q=function(){return""+this.p};function Ia(){var a=new O;a.p=!1;return a}O.prototype.a=B({ja:0},"scala.runtime.BooleanRef",{ja:1,b:1,d:1});
var ma=B({ka:0},"scala.runtime.BoxedUnit",{ka:1,b:1,d:1},void 0,void 0,function(a){return void 0===a});function P(){}P.prototype=new D;P.prototype.constructor=P;function Q(){}Q.prototype=P.prototype;var la=B({U:0},"java.lang.Boolean",{U:1,b:1,d:1,f:1},void 0,void 0,function(a){return"boolean"===typeof a});function R(){this.C=null}R.prototype=new Ma;R.prototype.constructor=R;R.prototype.c=function(){S=this;this.C=M(new L,Ka().M);M(new L,Ka().H);M(new L,null);return this};
R.prototype.a=B({ea:0},"scala.Console$",{ea:1,ra:1,b:1,ta:1});var S=void 0;function Ha(){S||(S=(new R).c());return S}function T(){this.z=null}T.prototype=new D;T.prototype.constructor=T;T.prototype.c=function(){U=this;this.z=y(0,0);return this};
function Oa(a,b){if(0===(-2097152&b))return""+(4294967296*b+ +(a>>>0));var c=(32+n(1E9)|0)-(0!==b?n(b):32+n(a)|0)|0,d=c,g=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,f=a,k=b;for(a=b=0;0<=c&&0!==(-2097152&k);){var l=f,t=k,La=g,qa=d;if(t===qa?(-2147483648^l)>=(-2147483648^La):(-2147483648^t)>=(-2147483648^qa))l=k,t=d,k=f-g|0,l=(-2147483648^k)>(-2147483648^f)?-1+(l-t|0)|0:l-t|0,f=k,k=l,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;l=d>>>1|0;g=g>>>1|0|d<<31;d=l}c=k;if(0===c?-1147483648<=(-2147483648^
f):-2147483648<=(-2147483648^c))c=4294967296*k+ +(f>>>0),f=c/1E9,g=f/4294967296|0,d=b,b=f=d+(f|0)|0,a=(-2147483648^f)<(-2147483648^d)?1+(a+g|0)|0:a+g|0,c%=1E9,f=c|0,k=c/4294967296|0;b=[b,a,f,k];a=""+(b["2"]|0);return""+(4294967296*(b["1"]|0)+ +((b["0"]|0)>>>0))+"000000000".substring(a.length|0)+a}T.prototype.a=B({ha:0},"scala.scalajs.runtime.RuntimeLong$",{ha:1,b:1,sa:1,d:1});var U=void 0;function C(){U||(U=(new T).c());return U}function V(){}V.prototype=new Q;V.prototype.constructor=V;
function Pa(){}Pa.prototype=V.prototype;V.prototype.S=function(){return this};
var fa=B({R:0},"java.lang.String",{R:1,b:1,d:1,pa:1,f:1},void 0,void 0,function(a){return"string"===typeof a}),ga=B({V:0},"java.lang.Byte",{V:1,i:1,b:1,d:1,f:1},void 0,void 0,function(a){return a<<24>>24===a&&1/a!==1/-0}),ka=B({X:0},"java.lang.Double",{X:1,i:1,b:1,d:1,f:1},void 0,void 0,function(a){return"number"===typeof a}),ja=B({Y:0},"java.lang.Float",{Y:1,i:1,b:1,d:1,f:1},void 0,void 0,function(a){return"number"===typeof a}),ia=B({Z:0},"java.lang.Integer",{Z:1,i:1,b:1,d:1,f:1},void 0,void 0,function(a){return(a|
0)===a&&1/a!==1/-0});function W(){}W.prototype=new Q;W.prototype.constructor=W;W.prototype.c=function(){return this};W.prototype.a=B({aa:0},"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{aa:1,Q:1,b:1,O:1,P:1});var na=B({ba:0},"java.lang.Long",{ba:1,i:1,b:1,d:1,f:1},void 0,void 0,function(a){return!!(a&&a.a&&a.a.g.D)}),ha=B({ca:0},"java.lang.Short",{ca:1,i:1,b:1,d:1,f:1},void 0,void 0,function(a){return a<<16>>16===a&&1/a!==1/-0});function X(){this.u=this.w=0}X.prototype=new Na;
X.prototype.constructor=X;X.prototype.q=function(){C();var a=this.w,b=this.u;return b===a>>31?""+a:0>b?"-"+Oa(-a|0,0!==a?~b:-b|0):Oa(a,b)};function y(a,b){var c=new X;c.w=a;c.u=b;return c}X.prototype.B=function(){return this.w^this.u};X.prototype.a=B({D:0},"scala.scalajs.runtime.RuntimeLong",{D:1,i:1,b:1,d:1,f:1});function Y(){}Y.prototype=new Pa;Y.prototype.constructor=Y;function Qa(){}Qa.prototype=Y.prototype;Y.prototype.T=function(){V.prototype.S.call(this);return this};
function Z(){this.m=this.K=null}Z.prototype=new Qa;Z.prototype.constructor=Z;function Ja(a){var b=new Z;b.K=a;(new W).c();Y.prototype.T.call(b,0);b.m="";return b}function Ga(a,b){for(;""!==b;){var c=b.indexOf("\n")|0;if(0>c)a.m=""+a.m+b,b="";else{var d=""+a.m+b.substring(0,c);h.console&&(a.K&&h.console.error?h.console.error(d):h.console.log(d));a.m="";b=b.substring(1+c|0)}}}Z.prototype.a=B({$:0},"java.lang.JSConsoleBasedPrintStream",{$:1,ma:1,la:1,Q:1,b:1,O:1,P:1,oa:1});
}).call(this);
//# sourceMappingURL=example-opt.js.map
